# Generated by Django 5.1.1 on 2024-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_remove_subcategory_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
