# Generated by Django 5.1.1 on 2024-10-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, default='profile_pictures/default_profpic.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
