# Generated by Django 5.1.1 on 2024-10-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_payments/'),
        ),
    ]
