# Generated by Django 5.1.1 on 2024-11-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_user_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_payment',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_payments/'),
        ),
    ]
