# Generated by Django 5.1.1 on 2024-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_user_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
