# Generated by Django 5.1.1 on 2024-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_transaction_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_number',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
