# Generated by Django 5.1.1 on 2024-11-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_transaction_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
