# Generated by Django 5.1.1 on 2024-11-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_transaction_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profpic.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
