# Generated by Django 5.1.1 on 2025-05-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_notified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
